pipeline {
    agent { label 'slave-L1'}
    tools {
        maven 'Maven-3'
        jdk 'jdk17'
    }
    stages {
         stage('Compile') {
            steps {
                dir('Boardgame-main') {
                sh 'mvn compile'
                                      }
                 }
        }
         stage('Test') {
            steps {
                dir('Boardgame-main') {
                sh 'mvn test'
                                      }
                  }
        }
    }
}
